-- BLUE//LOG Supabase setup
-- Supabase SQL Editor にそのまま貼り付けて実行してください。

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 80),
  category text not null default '雑記',
  excerpt text not null default '',
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.posts(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 30),
  text text not null check (char_length(text) between 1 and 500),
  created_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);

alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.admin_users enable row level security;

-- Public can read posts/comments.
drop policy if exists "posts_public_read" on public.posts;
create policy "posts_public_read" on public.posts
  for select using (true);

drop policy if exists "comments_public_read" on public.comments;
create policy "comments_public_read" on public.comments
  for select using (true);

-- Anyone can submit a comment. Do not expose admin privileges through comments.
drop policy if exists "comments_public_insert" on public.comments;
create policy "comments_public_insert" on public.comments
  for insert with check (true);

-- Only registered admin users can create/update/delete posts.
drop policy if exists "posts_admin_insert" on public.posts;
create policy "posts_admin_insert" on public.posts
  for insert to authenticated
  with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

drop policy if exists "posts_admin_update" on public.posts;
create policy "posts_admin_update" on public.posts
  for update to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()))
  with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

drop policy if exists "posts_admin_delete" on public.posts;
create policy "posts_admin_delete" on public.posts
  for delete to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()));

-- The admin_users table itself must never be readable/writable from the browser.
drop policy if exists "admin_users_none" on public.admin_users;
create policy "admin_users_none" on public.admin_users
  for all using (false) with check (false);

-- Helpful indexes.
create index if not exists posts_created_at_idx on public.posts(created_at desc);
create index if not exists posts_category_idx on public.posts(category);
create index if not exists comments_post_id_idx on public.comments(post_id, created_at asc);
